apiVersion: v1
items:
- apiVersion: external-secrets.io/v1beta1
  kind: SecretStore
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"external-secrets.io/v1beta1","kind":"SecretStore","metadata":{"annotations":{},"name":"doppler-auth-api","namespace":"doppler"},"spec":{"provider":{"doppler":{"auth":{"secretRef":{"dopplerToken":{"key":"dopplerToken","name":"doppler-token-auth-api"}}}}}}}
    creationTimestamp: "2024-04-07T18:44:08Z"
    generation: 1
    name: doppler-auth-api
    namespace: doppler
    resourceVersion: "2482919"
    uid: 69124ee4-45a6-46cb-b059-5f6cd04305f6
  spec:
    provider:
      doppler:
        auth:
          secretRef:
            dopplerToken:
              key: dopplerToken
              name: doppler-token-auth-api
  status:
    capabilities: ReadOnly
    conditions:
    - lastTransitionTime: "2024-04-13T09:06:44Z"
      message: store validated
      reason: Valid
      status: "True"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
