apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-github-private-key
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-github-private-key

  data:
    - secretKey: GITHUB_PRIVATE_KEY
      remoteRef:
        key: GITHUB_PRIVATE_KEY
