apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-github-key
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-github-key

  data:
    - secretKey: GITHUB_KEY
      remoteRef:
        key: GITHUB_KEY
